inherit_from: .rubocop_todo.yml

require:
  - 'rubocop-performance'
  - 'rubocop-rails'

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.0

Layout/LineLength:
  Enabled: false
  Max: 80

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Allow both single-quoted and double-quoted string literals.
Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SignalException:
  Exclude:
    - 'config/initializers/warden.rb'

# Allow non-alphabetical Gemfiles.
Bundler/OrderedGems:
  Enabled: false
