module.exports = {
  content: [
    './app/views/**/*.{html,html.erb}',
    './app/helpers/**/*.rb',
    './app/frontend/**/*.{js,ts,css,scss}',
    './app/components/**/*.{html.erb,rb}',
  ],
  theme: {
    extend: {
      colors: {
        transparent: 'transparent',
        pearl: '#F0F0F0',

        /* RubyAU Custom colours */
        pink: {
          DEFAULT: '#F71264',
          darkest: '#4A051E',
          darker: '#940B3C',
          dark: '#DE105A',
          light: '#F95993',
          lighter: '#FCA0C1',
          lightest: '#FEE7F0',
        },
        purple: {
          DEFAULT: '#793AE9',
          darkest: '#241146',
          darker: '#49238C',
          dark: '#6D34D2',
          light: '#A175F0',
          lighter: '#C9B0F6',
          lightest: '#F2EBFD',
        },
        cyan: {
          DEFAULT: '#49F1E4',
          darkest: '#164844',
          darker: '#2C9189',
          dark: '#42D9CD',
          light: '#80F5EC',
          lighter: '#B6F9F4',
          lightest: '#EDFEFC',
        },

        /* Standard Tailwind colors (simplified) */
        black: '#22292f',
        grey: {
          DEFAULT: '#b8c2cc',
          darkest: '#3d4852',
          darker: '#606f7b',
          dark: '#8795a1',
          light: '#dae1e7',
          lighter: '#f1f5f8',
          lightest: '#f8fafc',
        },
        white: '#ffffff',
        red: {
          DEFAULT: '#e3342f',
          darkest: '#3b0d0c',
          darker: '#621b18',
          dark: '#cc1f1a',
          light: '#ef5753',
          lighter: '#f9acaa',
          lightest: '#fcebea',
        },
        orange: {
          DEFAULT: '#f6993f',
          darkest: '#462a16',
          darker: '#613b1f',
          dark: '#de751f',
          light: '#faad63',
          lighter: '#fcd9b6',
          lightest: '#fff5eb',
        },
        yellow: {
          DEFAULT: '#ffed4a',
          darkest: '#453411',
          darker: '#684f1d',
          dark: '#f2d024',
          light: '#fff382',
          lighter: '#fff9c2',
          lightest: '#fcfbeb',
        },
        green: {
          DEFAULT: '#38c172',
          darkest: '#0f2f21',
          darker: '#1a4731',
          dark: '#1f9d55',
          light: '#51d88a',
          lighter: '#a2f5bf',
          lightest: '#e3fcec',
        },
        teal: {
          DEFAULT: '#4dc0b5',
          darkest: '#0d3331',
          darker: '#20504f',
          dark: '#38a89d',
          light: '#64d5ca',
          lighter: '#a0f0ed',
          lightest: '#e8fffe',
        },
        blue: {
          DEFAULT: '#3490dc',
          darkest: '#12283a',
          darker: '#1c3d5a',
          dark: '#2779bd',
          light: '#6cb2eb',
          lighter: '#bcdefa',
          lightest: '#eff8ff',
        },
        indigo: {
          DEFAULT: '#6574cd',
          darkest: '#191e38',
          darker: '#2f365f',
          dark: '#5661b3',
          light: '#7886d7',
          lighter: '#b2b7ff',
          lightest: '#e6e8ff',
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
    require('@tailwindcss/typography'),
  ],
};
