require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/elections", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Election. As you add validations to Election, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Election.create! valid_attributes
      get elections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      election = Election.create! valid_attributes
      get election_url(election)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_election_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      election = Election.create! valid_attributes
      get edit_election_url(election)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Election" do
        expect {
          post elections_url, params: { election: valid_attributes }
        }.to change(Election, :count).by(1)
      end

      it "redirects to the created election" do
        post elections_url, params: { election: valid_attributes }
        expect(response).to redirect_to(election_url(Election.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Election" do
        expect {
          post elections_url, params: { election: invalid_attributes }
        }.to change(Election, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post elections_url, params: { election: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested election" do
        election = Election.create! valid_attributes
        patch election_url(election), params: { election: new_attributes }
        election.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the election" do
        election = Election.create! valid_attributes
        patch election_url(election), params: { election: new_attributes }
        election.reload
        expect(response).to redirect_to(election_url(election))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        election = Election.create! valid_attributes
        patch election_url(election), params: { election: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested election" do
      election = Election.create! valid_attributes
      expect {
        delete election_url(election)
      }.to change(Election, :count).by(-1)
    end

    it "redirects to the elections list" do
      election = Election.create! valid_attributes
      delete election_url(election)
      expect(response).to redirect_to(elections_url)
    end
  end
end
